import assert from 'node:assert/strict';
import test from 'node:test';
import {fileURLToPath} from 'node:url';
import {createServer} from 'vite';

test('map readiness waits for the character, aborted loading releases its scene, failed images retry',async()=>{
 const root=fileURLToPath(new URL('..',import.meta.url));
 const vite=await createServer({appType:'custom',configFile:false,root,resolve:{alias:{'@':root}},server:{middlewareMode:true,hmr:false}});
 const {createMapEngine}=await vite.ssrLoadModule('/features/world/map-engine.ts');
 const {WORLD_ART}=await vite.ssrLoadModule('/features/world/art.ts');
 const {MAP_PLACES}=await vite.ssrLoadModule('/features/world/map-layout.ts');
 const {connectHabitat}=await vite.ssrLoadModule('/features/mochlik/session.ts');
 const {mountHabitat}=await vite.ssrLoadModule('/features/mochlik/scene.ts');
 const {BIRD_FLIGHTS,birdFlightPose}=await vite.ssrLoadModule('/features/world/bird-ambience.ts');
 const {loadHabitatImage,HabitatAssetError}=await vite.ssrLoadModule('/features/mochlik/assets.ts');await vite.close();
 const original=new Map(),pending=[],timers=new Map(),frames=new Map();let id=0,observed=0;
 const install=(name,value)=>{original.set(name,Object.getOwnPropertyDescriptor(globalThis,name));Object.defineProperty(globalThis,name,{value,writable:true,configurable:true})};
 const pixels=(w,h)=>{const data=new Uint8ClampedArray(w*h*4).fill(255);data[0]=data[1]=data[2]=0;return {data}};
 const translations=[];
 const ctx=new Proxy({translate:(x,y)=>translations.push({x,y}),getImageData:(_x,_y,w,h)=>pixels(w,h),createImageData:pixels,createRadialGradient:()=>({addColorStop(){}}),createLinearGradient:()=>({addColorStop(){}})}, {get:(object,key)=>key in object?object[key]:()=>{}});
 const canvas=()=>({width:256,height:256,clientWidth:393,clientHeight:740,getContext:()=>ctx,addEventListener(){},removeEventListener(){},hasPointerCapture(){return false}});
 install('Image',class {naturalWidth=1254;naturalHeight=1254;set src(path){if(!path)return;this.naturalWidth=this.naturalHeight=path===WORLD_ART.homePreview?256:path===WORLD_ART.mapPreview?384:1254;pending.push({path,image:this})}});
 install('document',{hidden:false,createElement:canvas,addEventListener(){},removeEventListener(){}});install('window',{});
 install('setTimeout',(fn,ms)=>{timers.set(++id,{fn,ms});return id});install('clearTimeout',key=>timers.delete(key));
 install('requestAnimationFrame',fn=>{frames.set(++id,fn);return id});install('cancelAnimationFrame',key=>frames.delete(key));
 for(const type of ['ResizeObserver','IntersectionObserver'])install(type,class{observe(){observed++}disconnect(){observed--}});
 const flush=()=>new Promise(resolve=>setImmediate(resolve));
 const finish=path=>{const at=pending.findIndex(item=>item.path===path);assert.ok(at>=0,path);pending.splice(at,1)[0].image.onload?.()};
 try{
  const options={paused:false,reducedMotion:false,lampOn:false,dusk:false,presenceKey:'cancel-map'};
  const abort=new AbortController();let ready=false;
  const first=createMapEngine(canvas(),options,()=>{},[],abort.signal).then(v=>{ready=true;return v});
  const cancelled=assert.rejects(first,error=>error.name==='AbortError');
  assert.equal(ready,false);assert.equal(observed,0);assert.equal(frames.size,0);
  abort.abort();finish(WORLD_ART.mapPreview);finish(WORLD_ART.homePreview);await cancelled;await flush();
  assert.equal(observed,0);assert.equal(frames.size,0);assert.equal(timers.size,0);
  assert.equal(pending.length,0,"only lightweight previews are needed before the view mounts");
  const bush={dataset:{kind:'bush',...MAP_PLACES.bush.marker},style:{}};
  const house={dataset:{kind:'house',...MAP_PLACES.house.marker},style:{}};
  const surface=canvas();
  const engine=await createMapEngine(surface,options,()=>{},[bush,house]);assert.equal(observed,3);
  assert.ok(pending.some(item=>item.path===WORLD_ART.map),'the complete scene is already interactive while full artwork is downloading');
  finish(WORLD_ART.map);await flush();
  finish(WORLD_ART.boatWreck);await flush();
  // An already-running flight keeps its actual source-map position in either renderer.
  const shared=connectHabitat(options.presenceKey,'circle',false,()=>assert.fail('reuse map state'),()=>{});
  translations.length=0;engine.control('pet');
  const petX=486+shared.world.state.position.x*256;
  const petY=514+(shared.world.state.position.y-shared.world.state.size*.5-shared.world.state.lift)*256;
  assert.ok(translations.some(point=>Math.abs(point.x+petX)<1e-8&&Math.abs(point.y+petY)<1e-8),'the crosshair centers the actual character, not the clearing');
  shared.world.state.elapsed=41.5;
  const bird=birdFlightPose(BIRD_FLIGHTS[1],41.5,0);
  assert.ok(bird.x>=486&&bird.x<=742&&bird.y>=514&&bird.y<=770,'flight crosses the home crop');
  const seesBird=()=>translations.some(point=>Math.abs(point.x-bird.x)<1e-8&&Math.abs(point.y-bird.y)<1e-8);
  translations.length=0;engine.control('home');assert.ok(seesBird(),'map samples the shared flight, not a new timer');
  translations.length=0;
  const circle=mountHabitat(canvas(),{...options,view:'circle',paused:true},{activity(){},ready(){},failure(error){throw error}});
  await flush();assert.ok(seesBird(),'circle draws the same bird in world coordinates');
  assert.equal(circle.ambience().elapsed,41.5,'changing view never resets bird time');
  circle.dispose();shared.release();translations.length=0;engine.control('overview');
  const detail=pending.find(item=>item.path===WORLD_ART.homeDetail);assert.ok(detail);
  pending.splice(pending.indexOf(detail),1);detail.image.onerror();await flush();
  assert.equal(observed,3,'failed detail keeps the base map and character mounted');
  assert.equal(bush.style.visibility,'hidden','tiny overlapping bush target is suppressed in overview');
  assert.equal(house.style.visibility,'visible');
  engine.control('home');assert.equal(bush.style.visibility,'visible');
  engine.control('overview');assert.equal(bush.style.visibility,'hidden');
  engine.update({...options,paused:true});assert.equal(frames.size,0,'paused map and habitat stop both animation loops');
  engine.update({...options,backgrounded:true});assert.equal(frames.size,0,'backgrounded map cannot restart its detached habitat');
  engine.update({...options,reducedMotion:true});assert.equal(frames.size,0,'reduced motion has no water or habitat RAF');
  engine.update(options);assert.equal(frames.size,2,'resume keeps the original two loops, no additional water timer');
  engine.dispose();await flush();
  assert.equal(observed,0);assert.equal(frames.size,0);assert.equal(timers.size,0);
  // A disposed view must not restart animation when the shared detail arrives.
  const late=await createMapEngine(canvas(),options,()=>{},[]);
  late.dispose();finish(WORLD_ART.homeDetail);await flush();
  assert.equal(observed,0);assert.equal(frames.size,0);assert.equal(timers.size,0);
  const stalled=loadHabitatImage('/qa-timeout.webp');const failed=assert.rejects(stalled,error=>error instanceof HabitatAssetError&&error.timedOut);
  const timer=[...timers.values()].find(value=>value.ms===15000);assert.ok(timer);timer.fn();await failed;
  const old=pending.shift().image;assert.equal(old.onload,null);
  const retry=loadHabitatImage('/qa-timeout.webp');finish('/qa-timeout.webp');await retry;assert.equal(timers.size,0);
 } finally {for(const [name,descriptor]of original){if(descriptor)Object.defineProperty(globalThis,name,descriptor);else delete globalThis[name]}}
});
