// Generated by scripts/prepare-brand-assets.mjs from the supplied art/brand masters.
export const BRAND_LOGO_SRC = "/brand/zhiv-logo.webp?v=32bfaff14e31";
export const BRAND_ICON_32_SRC = "/icon-32.png?v=6cdf953ddaf6";
export const BRAND_ICON_192_SRC = "/icon-192.png?v=a1baa5050162";
export const BRAND_ICON_512_SRC = "/icon-512.png?v=795a64335f62";
export const BRAND_MASKABLE_ICON_SRC = "/icon-maskable-512.png?v=795a64335f62";
export const BRAND_APPLE_ICON_SRC = "/apple-touch-icon.png?v=6fc1ed677122";
export const BRAND_FAVICON_SRC = "/favicon.ico?v=5b65fe5907a7";
