import { economyCatalog, type EconomyFishingShop, type EconomyState } from "./model";
import { fishingState } from "./fishing";
import { secureRareInteger, type RareRandomInteger } from "./rare-drops";

// Identical integer selection weights in EconomyFishingShop.kt. Draws happen only on
// the authenticated server and the selected stock is saved, never regenerated by a render.
const rarityWeight: Record<string, number> = { common: 100, uncommon: 60, rare: 25, epic: 10, legendary: 4 };
type Candidate = Omit<EconomyFishingShop["offers"][number], "id"> & { weight: number };
export function createFishingShop(state: Pick<EconomyState, "buildings" | "fishing">, now: number,
  random: RareRandomInteger = secureRareInteger, shopId = crypto.randomUUID()): EconomyFishingShop {
  const catalog = economyCatalog.fishing!;
  const home = state.buildings.home ?? 1, current = fishingState(state), config = catalog.shop;
  const rods: Candidate[] = catalog.rods.filter(item => item.price > 0 && item.requiredHomeLevel <= home && !current.ownedRods.includes(item.id))
    .map(item => ({ kind: "rod", itemId: item.id, unitPrice: item.price, remaining: 1, weight: rarityWeight[item.rarity] }));
  const hooks: Candidate[] = catalog.hooks.filter(item => item.price > 0 && item.requiredHomeLevel <= home && !current.ownedHooks.includes(item.id))
    .map(item => ({ kind: "hook", itemId: item.id, unitPrice: item.price, remaining: 1, weight: rarityWeight[item.rarity] }));
  const baits: Candidate[] = catalog.baits.filter(item => item.requiredHomeLevel <= home)
    .map(item => ({ kind: "bait", itemId: item.itemId, unitPrice: item.price, remaining: config.baitStock, weight: rarityWeight[item.rarity] }));
  const chosen: Candidate[] = [];
  function take(pool: Candidate[]) {
    if (!pool.length) return;
    const total = pool.reduce((sum, item) => sum + item.weight, 0);
    let draw = random(total);
    if (!Number.isInteger(draw) || draw < 0 || draw >= total) throw new Error("Invalid trusted shop draw");
    for (let index = 0; index < pool.length; index++) {
      draw -= pool[index].weight;
      if (draw < 0) { chosen.push(...pool.splice(index, 1)); return; }
    }
  }
  take(rods); take(hooks); take(baits); take(baits);
  // Owning all permanent tackle frees its slots for the remaining bait varieties.
  while (chosen.length < config.slots && baits.length) take(baits);
  return { id: shopId, openedAt: new Date(now).toISOString(), refreshAt: new Date(now + config.refreshSeconds * 1000).toISOString(),
    refreshPricePearls: config.refreshPricePearls,
    offers: chosen.map(item => ({ id: `${shopId}:${item.itemId}`, kind: item.kind, itemId: item.itemId, unitPrice: item.unitPrice, remaining: item.remaining })) };
}
export function fishingShopExpired(shop: EconomyFishingShop | null | undefined, now: number): boolean {
  return !shop || now >= Date.parse(shop.refreshAt);
}
